# Generated by Django 5.0.6 on 2024-06-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_ournews'),
    ]

    operations = [
        migrations.AddField(
            model_name='ournews',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
