# Generated by Django 5.0.6 on 2024-06-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_ournews_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
