# Generated by Django 5.0.6 on 2024-06-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0009_furniture_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefits',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
