# Generated by Django 5.0.6 on 2024-06-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='News Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('is_published', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('owner', models.CharField(max_length=155, verbose_name='Owner')),
            ],
        ),
    ]
