# Generated by Django 5.0.6 on 2024-06-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0004_furniture_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Discount Name')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('owner', models.CharField(max_length=155, verbose_name='Owner')),
                ('description', models.TextField()),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('is_published', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='OurNews',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='furniture',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
