# Generated by Django 5.0.6 on 2024-06-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0006_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefits', models.TextField(verbose_name='Benefits')),
            ],
        ),
        migrations.CreateModel(
            name='WeHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Sarlavha')),
                ('description', models.TextField()),
                ('photo1', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('photo2', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('photo3', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
            ],
        ),
    ]
