# Generated by Django 5.0.7 on 2024-07-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0010_benefits_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={},
        ),
    ]
